- name: copy templates for password policies
  template: src={{ item }}
            dest={{ openldap.config_dir }}/{{ item | basename }}
  with_fileglob: ../templates/password_policy/*
  when: openldap.password_policy_enabled|bool

- name: check if ppolicy is part of the schema
  shell: ldapsearch -Y EXTERNAL -H ldapi:/// -s sub -b cn=config objectclass=olcSchemaConfig | grep ppolicy
  register: ppolicy_out
  ignore_errors: yes
  changed_when: False

- name: add password policy schema
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f  /etc/ldap/schema/ppolicy.ldif
  when: ppolicy_out.stdout.count("ppolicy,") < 1 and
        openldap.password_policy_enabled|bool

- name: check if policy container is created
  shell: ldapsearch -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} -b {{ openldap.suffix }} -s sub ou={{ openldap.password_policy_ou }}
  register: pcont_out
  ignore_errors: yes
  changed_when: False

- name: create policy container
  shell: ldapadd -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} -f {{ openldap.config_dir }}/ppolicy_container.ldif
  when: pcont_out.stdout.count("{{ openldap.password_policy_ou_dn }}") < 1 and
        openldap.password_policy_enabled|bool

- name: check if ppolicy module is registered
  shell: ldapsearch -Y EXTERNAL -H ldapi:/// -s sub -b olcDatabase={1}hdb,cn=config objectclass=olcPPolicyConfig
  register: pm_out
  ignore_errors: yes
  changed_when: False

- name: add password policy module
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap.config_dir }}/ppolicy_module.ldif
  when: pm_out.stdout.count(",ou={{ openldap.password_policy_ou }}") < 1 and
        openldap.password_policy_enabled|bool

- name: check if default policy is created
  shell: ldapsearch -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} -b {{ openldap.password_policy_ou_dn }} -s sub objectClass=pwdPolicy
  register: dpolicy_out
  ignore_errors: yes
  changed_when: False

- name: add default policy
  shell: ldapadd -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} -f {{ openldap.config_dir }}/password_policy.ldif
  when: openldap.password_policy_enabled|bool and
        (dpolicy_out.stdout.count("cn={{ openldap.password_policy_cn }}") < 1)

- name: delete the policy if policy is changed from enabled to disabled.
  shell: ldapdelete -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} {{ openldap.password_policy_dn }}
  when: dpolicy_out.stdout.count("cn={{ openldap.password_policy_cn }}") > 0 and
        openldap.password_policy_enabled|bool == False
