#!/bin/bash
set -eu
source $(dirname $0)/common
source $HOME/.stackrc

ansible-playbook \
  --inventory-file envs/test/hosts \
  --module-path ./library \
  $root/playbooks/tests/tasks/instances/delete.yml
