#!/bin/bash
set -eu
source $(dirname $0)/common

cd $root
export ANSIBLE_SSH_ARGS="$ssh_args"

ansible-playbook \
  --inventory-file envs/example/hosts \
  --module-path ./library \
  --connection ssh \
  --user $login_user \
  --sudo \
  playbooks/site.yml
