#!/usr/bin/env bash

ACTION=all
if [ $# -gt 0 ]; then
    ACTION=$1
fi

shift

if [ "${ACTION}" != "all" -a "${ACTION}" != "test" -a "${ACTION}" != "deploy" -a "${ACTION}" != "cleanup" -a "${ACTION}" != 'unit' -a "${ACTION}" != 'upgrade' ]; then
  echo "Usage: run [unit | test | deploy | cleanup | upgrade] [EXTRA ANSIBLE ARGS]"
  exit 1
fi

source $(dirname $0)/common

cd ${ROOT}

if [ "${ACTION}" == "all" -o "${ACTION}" == "unit" ]; then
  tox
  ring_bell
fi

if [ "${ACTION}" == "all" -o "${ACTION}" == "deploy" ]; then
  time $(ansible_command \
    "envs/test/hosts" \
    ${LOGIN_USER} \
    "site.yml $@" \
    "true")
  ring_bell
fi

if [ "${ACTION}" == "all" -o "${ACTION}" == "test" ]; then
  time $(ansible_command \
    "envs/test/hosts" \
    ${LOGIN_USER} \
    ${ROOT}/playbooks/tests/tasks/main.yml  $@ \
    "true")
  ring_bell
fi

if [ "${ACTION}" == "all" -o "${ACTION}" == "cleanup" ]; then
  time $(ansible_command \
    "envs/test/hosts" \
    ${LOGIN_USER} \
    ${ROOT}/playbooks/tests/tasks/cleanup.yml \
    "true")
  ring_bell
fi

if [ "${ACTION}" == "upgrade" ]; then
  time $(ansible_command \
    "envs/test/hosts" \
    ${LOGIN_USER} \
    "upgrade.yml $@" \
    "true")
  ring_bell
fi

echo "test complete"
