#!/usr/bin/env python

import re
import os
import daemon
import subprocess

with daemon.DaemonContext():
  # 3: wlan0    inet 108.179.186.215/23 brd 108.179.187.255 scope global wlan0
  ipadd = re.compile('(\d+):\s+(\S+)\s+inet\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).*')
  # Deleted 3: wlan0    inet 108.179.186.215/23 brd 108.179.187.255 scope global wlan0
  ipdel = re.compile('Deleted (\d+):\s+(\S+)\s+inet\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).*')

  ipmonitor = subprocess.Popen(['/sbin/ip', 'monitor', 'address'], stdout=subprocess.PIPE)

  while True:
    line = ipmonitor.stdout.readline()
    if line == '':
      break

    m = ipadd.match(line)
    if m:
      ifIndex = m.group(1)
      ifName = m.group(2)
      ipAddress = m.group(3)
      action = "/etc/ipchanged/" + ifName + "/" + ipAddress + "/add"
      if os.path.isfile(action) and os.access(action, os.X_OK):
        subprocess.call(action)

    m = ipdel.match(line)
    if m:
      ifIndex = m.group(1)
      ifName = m.group(2)
      ipAddress = m.group(3)
      action = "/etc/ipchanged/" + ifName + "/" + ipAddress + "/delete"
      if os.path.isfile(action) and os.access(action, os.X_OK):
        subprocess.call(action)
