---
- hosts: all
  roles:
    - common

- name: rabbitmq used by openstack
  hosts: controller
  serial: 1
  roles:
    - rabbitmq

- name: replicated db setup
  include: playbooks/percona.yml

- name: nova code and config
  hosts: controller:db:compute
  vars_files:
    - roles/memcached/defaults/main.yml
    - roles/rabbitmq/defaults/main.yml
  roles:
    - nova-common

- name: neutron code and config
  hosts: controller:db:compute:network
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - neutron-common

- name: glance code and config
  hosts: controller:db
  roles:
    - glance-common

- name: keystone code and config
  hosts: controller:db
  vars_files:
    - roles/memcached/defaults/main.yml
  roles:
    - keystone-common

- name: cinder code and config
  hosts: controller:db:compute
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - cinder-common

- name: barbican code and config
  hosts: controller:db
  roles:
    - barbican

- name: dbs, db users, db schema updates
  hosts: db[0]
  roles:
    - db

- name: openstack controller services
  hosts: controller
  roles:
    - client
    - memcached
    - horizon
    - controller

- hosts: compute
  roles:
    - compute
    - cinder-volume

- hosts: network:compute
  roles:
    - openvswitch

- name: openstack network services
  hosts: network
  roles:
    - network

- hosts: controller[0]
  roles:
    - openstack-setup

- name: Install monitoring
  include: playbooks/monitoring.yml
