require 'spec_helper'

dirs = ['/etc/heat', '/var/log/heat']
dirs.each do |dir|
  describe file(dir) do
    it { should be_directory }
    it { should be_mode '755'}
  end
end

files = ['api-paste.ini', 'policy.json',
  'heat.conf', 'heat_api_audit_map.conf']
files.each do |file|
  describe file("/etc/heat/#{file}") do
    it { should be_mode '644'}
  end
end

{% if inventory_hostname in groups['controller'] %}
processes = ['heat-api',
  'heat-engine',
  'heat-api-cfn']
processes.each do |process|
  describe process(process) do
    its(:user) { should eq 'heat' }
  end
end
{% endif %}
describe file('/etc/logrotate.d/heat') do
  it { should exist }
  file_contents = [ '# Generated by Ansible.',
         '# Local modifications will be overwritten.',
         '',
         '/var/log/heat/*.log',
         '{',
         '  daily',
         '  missingok',
         '  rotate 7',
         '  compress',
         '}']

  file_contents.each do |file_line|
    it { should contain file_line}
  end
end

files = Dir['/var/log/heat/*.*'].map { |a| File.basename(a) }
files.each do |file|
  describe file("/var/log/heat/#{file}") do
    it { should be_mode 644 }
  end
end

describe file("/etc/heat/heat.conf") do
  it { should contain '^debug = {{ heat.logging.debug }}' }
end