---
- name: install ceilometer compute service
  upstart_service: name=ceilometer-agent-compute
                   user=ceilometer
                   cmd=/usr/local/bin/ceilometer-agent-compute
  notify: restart ceilometer services

- name: install libvirt-python in package venv
  command: "{{ 'ceilometer'|ursula_package_path(openstack_package_version) }}/bin/pip install libvirt-python"
  notify: restart ceilometer services
  when: openstack_install_method == 'package'

- name: install libvirt-python in source venv
  command: "{{ openstack_source.virtualenv_base }}/ceilometer/bin/pip install libvirt-python"
  notify: restart ceilometer services
  when: openstack_install_method == 'source'

- meta: flush_handlers

- name: start ceilometer-compute service
  service: name=ceilometer-agent-compute state=started

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
