require 'spec_helper'

files = ['account-server.conf', 'container-server.conf', 'dispersion.conf', 'drive-audit.conf', 'object-expirer.conf', 'object-server.conf', 'proxy-server.conf', 'swift.conf']
files.each do |file|  
  has_file = file("/etc/swift/#{file}").exists?
  describe file("/etc/swift/#{file}"), :if => has_file do 
    it { should be_owned_by 'swift' }
    it { should be_grouped_into 'swift' }
    it { should be_mode 640 }
  end      
end

describe file('/etc/swift/') do
  it { should be_owned_by 'swiftops' }
  it { should be_grouped_into 'swiftops' }
  it { should be_mode 755 } 
end 

files = ['account.log', 'container.log', 'object.log', 'proxy.log']
files.each do |file|
  has_file = file("/var/log/swift/#{file}").exists?
  describe file("/var/log/swift/#{file}"), :if => has_file do 
    it { should be_owned_by 'syslog' }
    it { should be_grouped_into 'adm' }
    it { should be_mode 640 }
  end     
end

describe file('/etc/logrotate.d/swift') do
  it { should exist }
  file_contents = [ '# Generated by Ansible.',
         '# Local modifications will be overwritten.',
         '',
         '/var/log/swift/*.log',
         '{',
         'daily',
         'missingok',
         'rotate 7',
         'compress',
         'notifempty',
         'nocreate', 
         'postrotate', 
         'reload rsyslog >/dev/null 2>&1 || true', 
         'endscript', 
         '}']
  file_contents.each do |file_line|
    it { should contain file_line }
  end
end

files = ['object-expirer.conf', 'drive-audit.conf', 'container-server.conf', 'proxy-server.conf', 'account-server.conf', 'object-server.conf']
files.each do |file|
  has_file = file("/etc/swift/#{file}").exists?
  describe file("/etc/swift/#{file}"), :if => has_file do
    it { should contain '^log_level = INFO' }
  end   
end 
