---
- name: fail on unsupported system
  fail: "msg=system not supported {{ ansible_system }}"
  when: "ansible_system not in ['Linux']"

- name: fail on unsupported architecture
  fail: "msg=architecture not supported {{ ansible_architecture }}"
  when: "ansible_architecture not in ['x86_64']"

- name: fail on unsupported distribution
  fail: "msg=distribution not supported {{ ansible_os_family }}"
  when: "ansible_os_family not in ['Debian']"

- name: make sure an installation source was chosen
  fail: msg="please choose an installation source"
  when: not ceph_common.ceph_stable

- name: make sure journal_size configured
  fail: msg="journal_size must be configured"
  when: ceph_common.journal_size|int == 0

- name: make sure monitor_interface configured
  fail: msg="monitor_interface must be configured"
  when: ceph_common.monitor_interface == 'interface'

- name: make sure raw_multi_journal was chosen
  fail: msg="please choose an osd scenario"
  when: ceph_common.osd_group_name is defined and
        not ceph_osd.raw_multi_journal

- name: verify devices have been provided
  fail: msg="please provide devices to your osd scenario"
  when: osd_group_name is defined and
        ceph_osd.raw_multi_journal and
        ceph_osd.devices is not defined

- name: verify journal devices have been provided
  fail: msg="please provide journal devices to your osd scenario"
  when: osd_group_name is defined and
        ceph_osd.raw_multi_journal and
        ceph_osd.raw_journal_devices is not defined
