---
horizon:
  logo_url: https://s3.amazonaws.com/horizon-branding/bluebox-u1.1.x.png
  favicon_url: https://s3.amazonaws.com/horizon-branding/bluebox.ico
  keystone_api_version: 3
  session_timeout: 5400
  source:
    rev: 'kilo-bbg'
    python_dependencies:
      - { name: mysql-python }
      - { name: functools32 }
      - { name: python-memcached }
      - { name: python-memcached, version: '1.48' }
      - { name: stevedore, version: '1.5.0' }
    system_dependencies:
      - apache2
      - libapache2-mod-wsgi
      - libmysqlclient-dev
horizon_customization:
    git_repo: https://github.com/davidcusatis/bluebox-horizon-customization.git
    git_rev: master
    path: "{{ openstack_source.virtualenv_base}}/horizon/lib/python2.7/site-packages/bluebox-horizon-customization"
