#!/bin/sh
#
#
# OpenStack DHCP Service (neutron-dhcp-agent)
#
# Description:  Manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource
#
# Authors: Emilien Macchi
# Mainly inspired by the Nova Network resource agent written by Emilien Macchi & Sebastien Han
#
# Support:      openstack@lists.launchpad.net
# License:      Apache Software License (ASL) 2.0
#
#
# See usage() function below for more details ...
#
# OCF instance parameters:
#   OCF_RESKEY_binary
#   OCF_RESKEY_config
#   OCF_RESKEY_plugin_config
#   OCF_RESKEY_user
#   OCF_RESKEY_pid
#   OCF_RESKEY_amqp_server_port
#   OCF_RESKEY_additional_parameters
#######################################################################
# Initialization:

# OCF_ROOT added by mpatterson@bluebox.net
OCF_ROOT="/usr/lib/ocf"

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

#######################################################################

# Fill in some defaults if no values are specified

OCF_RESKEY_binary_default="/usr/local/bin/neutron-dhcp-agent"
OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
OCF_RESKEY_plugin_config_default="/etc/neutron/dhcp_agent.ini"
OCF_RESKEY_user_default="neutron"

# modified by mpatterson@bluebox.net
OCF_RESKEY_pid_default="$HA_RSCTMP/neutron-dhcp-agent.pid"
OCF_RESKEY_amqp_server_port_default="5672"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
: ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
: ${OCF_RESKEY_plugin_config=${OCF_RESKEY_plugin_config_default}}
: ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
: ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
: ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}

#######################################################################

usage() {
    cat <<UEND
        usage: $0 (start|stop|validate-all|meta-data|status|monitor)

        $0 manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource 

        The 'start' operation starts the networking service.
        The 'stop' operation stops the networking service.
        The 'validate-all' operation reports whether the parameters are valid
        The 'meta-data' operation reports this RA's meta-data information
        The 'status' operation reports whether the networking service is running
        The 'monitor' operation reports whether the networking service seems to be working

UEND
}

meta_data() {
    cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="neutron-dhcp-agent">
<version>1.0</version>

<longdesc lang="en">
Resource agent for the OpenStack Neutron DHCP Service (neutron-dhcp-agent)
May manage a neutron-dhcp-agent instance or a clone set that 
creates a distributed neutron-dhcp-agent cluster.
</longdesc>
<shortdesc lang="en">Manages the OpenStack DHCP Service (neutron-dhcp-agent)</shortdesc>
<parameters>

<parameter name="binary" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack DHCP Server server binary (neutron-dhcp-agent)
</longdesc>
<shortdesc lang="en">OpenStack DHCP Server server binary (neutron-dhcp-agent)</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>

<parameter name="config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack Neutron Service (neutron-server) configuration file
</longdesc>
<shortdesc lang="en">OpenStack DHCP Server (neutron-server) config file</shortdesc>
<content type="string" default="${OCF_RESKEY_config_default}" />
</parameter>

<parameter name="plugin config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack DHCP Service (neutron-dhcp-agent) configuration file
</longdesc>
<shortdesc lang="en">OpenStack DHCP Server (neutron-dhcp-agent) config file</shortdesc>
<content type="string" default="${OCF_RESKEY_plugin_config_default}" />
</parameter>

<parameter name="user" unique="0" required="0">
<longdesc lang="en">
User running OpenStack DHCP Service (neutron-dhcp-agent)
</longdesc>
<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) user</shortdesc>
<content type="string" default="${OCF_RESKEY_user_default}" />
</parameter>

<parameter name="pid" unique="0" required="0">
<longdesc lang="en">
The pid file to use for this OpenStack DHCP Service (neutron-dhcp-agent) instance
</longdesc>
<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) pid file</shortdesc>
<content type="string" default="${OCF_RESKEY_pid_default}" />
</parameter>  

<parameter name="amqp_server_port" unique="0" required="0">                                                                                                                                                              
<longdesc lang="en">                                                                                                                                                                                                      
The listening port number of the AMQP server. Mandatory to perform a monitor check                                                                                                                                        
</longdesc>                                                                                                                                                                                                               
<shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
<content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
</parameter>      


<parameter name="additional_parameters" unique="0" required="0">
<longdesc lang="en">
Additional parameters to pass on to the OpenStack DHCP Service (neutron-dhcp-agent)
</longdesc>
<shortdesc lang="en">Additional parameters for neutron-dhcp-agent</shortdesc>
<content type="string" />
</parameter>

</parameters>

<actions>
<action name="start" timeout="20" />
<action name="stop" timeout="20" />
<action name="status" timeout="20" />
<action name="monitor" timeout="30" interval="20" />
<action name="validate-all" timeout="5" />
<action name="meta-data" timeout="5" />
</actions>
</resource-agent>
END
}

#######################################################################
# Functions invoked by resource manager actions

neutron_dhcp_agent_validate() {
    local rc

    check_binary $OCF_RESKEY_binary
    check_binary netstat

    # A config file on shared storage that is not available
    # during probes is OK.
    if [ ! -f $OCF_RESKEY_config ]; then
        if ! ocf_is_probe; then
            ocf_log err "Config $OCF_RESKEY_config doesn't exist"
            return $OCF_ERR_INSTALLED
        fi
        ocf_log_warn "Config $OCF_RESKEY_config not available during a probe"
    fi

    getent passwd $OCF_RESKEY_user >/dev/null 2>&1
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "User $OCF_RESKEY_user doesn't exist"
        return $OCF_ERR_INSTALLED
    fi

    true
}

neutron_dhcp_agent_status() {
    local pid
    local rc

    if [ ! -f $OCF_RESKEY_pid ]; then
        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) is not running"
        return $OCF_NOT_RUNNING
    else
        pid=`cat $OCF_RESKEY_pid`
    fi

    ocf_run -warn kill -s 0 $pid
    rc=$?
    if [ $rc -eq 0 ]; then
        return $OCF_SUCCESS
    else
        ocf_log info "Old PID file found, but OpenStack DHCP Server (neutron-dhcp-agent) is not running"
        return $OCF_NOT_RUNNING
    fi
}

neutron_dhcp_agent_monitor() {
    local rc
    local pid
    local os_rc_file=/root/stackrc
    
    neutron_dhcp_agent_status
    rc=$?

    # If status returned anything but success, return that immediately
    if [ $rc -ne $OCF_SUCCESS ]; then
        return $rc
    fi

    # Query neutron agent commands to verify that the agent service is actually alive
    # rather than just looking for a valid pid.
    #
    # source openstack rc file
    if [ -f $os_rc_file ]; then
      . $os_rc_file
    else
      echo "No Openstack Source File Exists at: $os_rc_file"
      return $OCF_NOT_RUNNING
    fi

    rc=$(/usr/local/bin/neutron agent-show `/usr/local/bin/neutron agent-list | grep -i dhcp | grep $(/bin/hostname) | awk '{print \$2}'` | grep -i alive | grep -i true > /dev/null 2>&1 && echo "pass" || echo "fail")

    if [ $rc != "pass" ]; then
        ocf_log err "Neutron DHCP Server is not connected to the Neutron server: $rc"
        return $OCF_NOT_RUNNING
    fi

    ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) monitor succeeded"
    return $OCF_SUCCESS
}

neutron_dhcp_agent_start() {
    local rc

    neutron_dhcp_agent_status
    rc=$?
    if [ $rc -eq $OCF_SUCCESS ]; then
        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already running"
        return $OCF_SUCCESS
    fi
    
    /sbin/start neutron-dhcp-agent
    rc=$?

    # Spin waiting for the server to come up.
    # Let the CRM/LRM time us out if required
    while true; do
    neutron_dhcp_agent_monitor
    rc=$?
    [ $rc -eq $OCF_SUCCESS ] && break
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) start failed"
        exit $OCF_ERR_GENERIC
    fi
    sleep 1
    done

    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) started"
    return $OCF_SUCCESS
}

neutron_dhcp_agent_stop() {
    local rc
    local pid

    neutron_dhcp_agent_status
    rc=$?
    if [ $rc -eq $OCF_NOT_RUNNING ]; then
        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already stopped"
        return $OCF_SUCCESS
    fi

    # Try stop via upstart
    /sbin/stop neutron-dhcp-agent
    rc=$?

    if [ $rc -ne 0 ]; then
        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) couldn't be stopped"
        exit $OCF_ERR_GENERIC
    fi

    test -e $OCF_RESKEY_pid && rm $OCF_RESKEY_pid
    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) stopped"
    return $OCF_SUCCESS
}

#######################################################################

case "$1" in
  meta-data)    meta_data
                exit $OCF_SUCCESS;;
  usage|help)   usage
                exit $OCF_SUCCESS;;
esac

# Anything except meta-data and help must pass validation
neutron_dhcp_agent_validate || exit $?

# What kind of method was invoked?
case "$1" in
  start)        neutron_dhcp_agent_start;;
  stop)         neutron_dhcp_agent_stop;;
  status)       neutron_dhcp_agent_status;;
  monitor)      neutron_dhcp_agent_monitor;;
  validate-all) ;;
  *)            usage
                exit $OCF_ERR_UNIMPLEMENTED;;
esac
