---
- name: install cinder controller services
  upstart_service: name={{ item }}
                   user=cinder
                   cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/cinder
  with_items:
    - cinder-api
    - cinder-scheduler

- name: install cinder backup service
  upstart_service: name=cinder-backup
                   user=cinder
                   cmd=/usr/local/bin/cinder-backup
                   config_dirs=/etc/cinder
  when: swift.enabled|default("false")|bool

- name: stop cinder services before db sync
  service: name={{ item }} state=stopped
  with_items:
    - cinder-api
    - cinder-scheduler
  when: database_create.changed or force_sync|default('false')|bool

- name: stop cinder backup service before db sync
  service: name=cinder-backup state=stopped
  when: swift.enabled|default("false")|bool

- name: sync cinder database
  command: cinder-manage db sync
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart cinder services
  # we want this to always be changed so that it can notify the service restart

- meta: flush_handlers

- name: start cinder controller services
  service: name={{ item }} state=started
  with_items:
    - cinder-api
    - cinder-scheduler

- name: start cinder backup
  service: name=cinder-backup state=started
  when: swift.enabled|default("false")|bool

- name: Permit access to Cinder
  ufw: rule=allow to_port={{ cinder.haproxy_api_port }} proto=tcp

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool
