---
- name: install cinder controller services
  upstart_service: name={{ item }}
                   user=cinder
                   cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/cinder
  with_items:
    - cinder-api
    - cinder-scheduler

- name: stop cinder services before db sync
  service: name={{ item }} state=stopped
  with_items:
    - cinder-api
    - cinder-scheduler
  when: database_create.changed or force_sync|default('false')|bool
  tags: db-migrate

- name: sync cinder database
  command: cinder-manage db sync
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart cinder services
  # we want this to always be changed so that it can notify the service restart
  tags: db-migrate

- meta: flush_handlers

- name: start cinder controller services
  service: name={{ item }} state=started
  with_items:
    - cinder-api
    - cinder-scheduler

- name: Permit access to Cinder
  ufw: rule=allow to_port={{ endpoints.cinder.port.haproxy_api }} proto=tcp

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool
