#!/bin/bash

. /root/stackrc

# Wait up to 5 minutes for Neutron to recover from MySQL and HAProxy cutover
TRIES=0
until neutron agent-list || [ $(( TRIES++ )) -eq 10 ]; do
  sleep 30
done

export HOSTNAME=$( hostname )
/usr/local/bin/migrate_neutron_services
