---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: swift
    logdata: "{{ swift.logs }}"
  - role: openstack-source
    project_name: swift
    python_requirements:
      - { name: python-keystoneclient, version: '1.0.0' }
      - { name: keystonemiddleware }
    project_rev: "{{ swift.source.rev }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: swift
    package_alternatives: "{{ swift.package.console_scripts }}"
    when: openstack_install_method == 'package'
