---
- name: install dependencies
  apt: pkg=parted
       state=present
  when: ansible_os_family == 'Debian'

- name: copy osd bootstrap key
  copy: src=fetch/{{ fsid }}/var/lib/ceph/bootstrap-osd/ceph.keyring
        dest=/var/lib/ceph/bootstrap-osd/ceph.keyring
        owner=root
        group=root
        mode=600
  when: cephx
