---
# NOTE: some devices might miss partition label which which will result
# in ceph-disk failing to prepare OSD. Thus zapping them prior to prepare the OSD
# ensures that the device will get successfully prepared.
- name: erasing partitions and labels from osd disk(s)
  command: ceph-disk zap {{ item.2 }}
  changed_when: false
  with_together:
    - parted.results
    - ispartition.results
    - ceph_osd.devices
  when:
    item.0.rc != 0 and
    item.1.rc != 0 and
    ceph_osd.zap_devices and
    (ceph_osd.journal_collocation or ceph_osd.raw_multi_journal)

- name: erasing partitions and labels from the journal device(s)
  command: ceph-disk zap {{ item.2 }}
  changed_when: false
  with_together:
    - parted.results
    - ispartition.results
    - ceph_osd.raw_journal_devices
  when:
    item.0.rc != 0 and
    item.1.rc != 0 and
    ceph_osd.zap_devices and
    ceph_osd.raw_multi_journal
