---
# cinder volume
- name: cinder-volume process check
  sensu_process_check: service=cinder-volume
  notify: restart sensu-client

- name: iscsid process check
  sensu_process_check: service=iscsid
  notify: restart sensu-client
  when: not ceph.enabled|default('False')|bool or (not ceph_pools.rbd_ssd.enabled and not ceph_pools.rbd_hybrid.enabled)

- name: cinder volume group metrics
  sensu_metrics_check:
    name: cinder-vg-metrics
    plugin: metrics-volgroup.sh
    args: '-v cinder-volumes -s {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client
  when: cinder.create_vg|bool and ( cinder.fixed_key is not defined or (cinder.fixed_key is defined and "compute" not in group_names) )

- name: cinder volume group metrics
  sensu_metrics_check:
    name: cinder-vg-metrics
    plugin: metrics-volgroup.sh
    args: '-v cinder-volumes -s {{ monitoring.graphite.host_prefix }}'
    state: absent
  notify: restart sensu-client
  when: ceph.enabled|default('False')|bool and (ceph_pools.rbd_ssd.enabled or ceph_pools.rbd_hybrid.enabled)

- name: cinder-backup process check
  sensu_process_check: service=cinder-backup
  notify: restart sensu-client
  when: swift.enabled|default("False")|bool
