#!/bin/bash
ips="{% for host in groups['compute'] -%}{{ hostvars[host][primary_interface]['ipv4']['address'] }} {% endfor -%}"

for ip in $ips; do
  echo testing ssh to $ip ...
  sudo -u nova -H /bin/sh -c "ssh $ip uptime"
done
