---
- include: primary.yml
  when: inventory_hostname in groups['mongo_db'][0]

- name: add mongodb secondary servers to replica set
  command: mongo --host {{ endpoints.mongodb }} --eval rs.add(\"{{ primary_ip ~ ":" ~ mongodb.port | string}}\")
  when: inventory_hostname not in groups['mongo_db'][0] and inventory_hostname in groups['mongo_db']
