---
## SCENARIO 2: N JOURNAL DEVICES FOR N OSDS

- include: tasks/check_devices.yml
- include: tasks/zap_devices.yml

# NOTE: the prepare process must be parallelized somehow...
# if you have 64 disks with 4TB each, this will take a while
# since Ansible will sequential process the loop

# NOTE: if the device is a partition, the parted command below has
# failed, this is why we check if the device is a partition too.
- name: prepare osd disk(s)
  command: "ceph-disk prepare {{ item.2 }} {{ item.3 }}"
  with_together:
    - parted.results
    - ispartition.results
    - ceph_osd.devices
    - ceph_osd.raw_journal_devices
  changed_when: false
  failed_when: false
  when:
    item.0.rc != 0 and
    item.1.rc != 0 and
    ceph_osd.raw_multi_journal

- include: tasks/activate_osds.yml
