---
- name: make sure an installation source was chosen
  fail: msg="choose an installation source or read https://github.com/ceph/ceph-ansible/wiki"
  when: not ceph_common.ceph_stable

- name: make sure journal_size configured
  fail: msg="journal_size must be configured. See http://ceph.com/docs/master/rados/configuration/osd-config-ref/"
  when: ceph_common.journal_size|int == 0

- name: make sure monitor_interface configured
  fail: msg="monitor_interface must be configured. Interface for the monitor to listen on"
  when: ceph_common.monitor_interface == 'interface'

- name: make sure cluster_network configured
  fail: msg="cluster_network must be configured. Ceph replication network"
  when: ceph_common.cluster_network == '0.0.0.0/0'

- name: make sure public_network configured
  fail: msg="public_network must be configured. Ceph public network"
  when: ceph_common.public_network == '0.0.0.0/0'

- name: make sure an osd scenario was chosen
  fail: msg="please choose an osd scenario"
  when: ceph_common.osd_group_name is defined and
        not ceph_osd.journal_collocation and
        not ceph_osd.raw_multi_journal and
        not ceph_osd.osd_directory

- name: verify only one osd scenario was chosen
  fail: msg="please select only one osd scenario"
  when: ceph_common.osd_group_name is defined and
        ((ceph_osd.journal_collocation and ceph_osd.raw_multi_journal) or
        (ceph_osd.journal_collocation and ceph_osd.osd_directory) or
        (ceph_osd.raw_multi_journal and ceph_osd.osd_directory))

- name: verify devices have been provided
  fail: msg="please provide devices to your osd scenario"
  when: osd_group_name is defined and
        (ceph_osd.journal_collocation or ceph_osd.raw_multi_journal) and
        ceph_osd.devices is not defined

- name: verify journal devices have been provided
  fail: msg="please provide devices to your osd scenario"
  when: osd_group_name is defined and
        ceph_osd.raw_multi_journal and
        ceph_osd.raw_journal_devices is not defined

- name: verify directories have been provided
  fail: msg="please provide directories to your osd scenario"
  when: osd_group_name is defined and
        ceph_common.osd_group_name in group_names and
        ceph_osd.osd_directory and
        ceph_osd.osd_directories is not defined
