---
- name: create openstack pool
  command: rados mkpool {{ item }}
  with_items:
    - "{{ openstack_cinder_pool }}"
  failed_when: false

- name: create openstack keys
  command: ceph auth get-or-create {{ item.name }} {{ item.value }} -o /etc/ceph/ceph.{{ item.name }}.keyring
           creates=/etc/ceph/ceph.{{ item.name }}.keyring
  with_items: openstack_keys
