---
- name: activate monitor with upstart
  file: path=/var/lib/ceph/mon/ceph-{{ ansible_hostname }}/{{ item }}
        state=touch
        owner=root
        group=root
        mode=0600
  with_items:
    - done
    - upstart
  when: ansible_distribution == "Ubuntu"
  changed_when: false

- name: start and add that the monitor service to the init sequence (ubuntu)
  service: name=ceph-mon
           state=started
           enabled=yes
           args="id={{ ansible_hostname }}"
  when: ansible_distribution == "Ubuntu"

- name: get ceph monitor version
  shell: ceph daemon mon."{{ ansible_hostname }}" version | cut -d '"' -f 4 | cut -f 1,2 -d '.'
  changed_when: false
  failed_when: "'No such file or directory' in ceph_version.stderr"
  register: ceph_version
