---
magnum:
  port: 9512
  host: 127.0.0.1
  source:
    rev: 'stable/kilo'
  package: ~
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  logs:
    - paths:
      - /var/log/magnum/something.log
      fields:
        type: openstack
        tags: magnum,keystone-something
  logging:
    debug: False
    verbose: True
