---
magnum:
  port: 9512
  host: 127.0.0.1
  source:
    rev: 'stable/kilo'
  package: ~
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  logs:
    - paths:
        - /var/log/magnum/magnum-api.log
      fields:
        type: openstack
        tags: magnum,magnum-api
    - paths:
        - /var/log/magnum/magnum-conductor.log
      fields:
        type: openstack
        tags: magnum,magnum-conductor
  logging:
    debug: False
    verbose: True
