---
#
# NOTE: this file is included by the prereboot tag, as such it should work not include anything that will break older releases
#
- name: install ipmitool
  apt: pkg=ipmitool

- name: load kernel ipmi modules
  modprobe: name={{ item }} state=probe
  with_items:
    - ipmi_devintf
    - ipmi_si

- include: serial-console.yml tty={{ common.ipmi.serial_console }} baud_rate=115200
