---
- name: neutron process checks
  sensu_process_check: service={{ item }}
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  notify: restart sensu-client

- name: neutron lbaas process check
  sensu_process_check: service=neutron-lbaasv2-agent
  notify: restart sensu-client
  when: neutron.lbaas.enable

- name: ipchanged process check
  sensu_process_check: service=/usr/local/sbin/ipchanged

- name: ucarp failover alert
  sensu_check: name=check-ucarp-failover plugin=check-log.rb use_sudo=true
               auto_resolve=false interval=20 occurrences=1
               args="-f /var/log/syslog -q 'ucarp.+[Ss]witching to state' --silent"
  notify: restart sensu-client

- name: ucarp processes check
  sensu_check: name=check-ucarp-procs plugin=check-ucarp-procs.sh use_sudo=true
  notify: restart sensu-client

- name: l3 router check
  sensu_check: name=check-l3-router plugin=check-l3-router.sh use_sudo=true
  notify: restart sensu-client
