---
- name: remove keystone eventlet check
  sensu_process_check: service=keystone-all state=absent
  notify: restart sensu-client

- name: keystone process check
  sensu_process_check: service=uwsgi
  notify: restart sensu-client

- name: shibboleth process check
  sensu_process_check: service=shibd
  notify: restart sensu-client
  when: keystone.federation.enabled|bool and keystone.federation.sp.saml.enabled|bool

- name: keystone-api check
  sensu_check: name=check-keystone-api plugin=check-os-api.rb
               args="--service keystone --criticality {{ keystone.monitoring.sensu_checks.check_keystone_api.criticality }}"
  notify: restart sensu-client

- name: keystone token buildup check
  sensu_check:
    name: check-keystone-expired-tokens
    plugin: check-keystone-expired-tokens.py
    interval: 10
    use_sudo: true
  notify: restart sensu-client

- name: keystone metrics
  template: src=etc/collectd/plugins/keystone.conf dest=/etc/collectd/plugins/keystone.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd

- name: keystone sla metrics
  sensu_metrics_check: name=keystone-sla-metrics plugin=metrics-os-api.py
                       args='-S keystone --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: keystone identity metrics
  sensu_metrics_check:
    name: identity-metrics
    plugin: metrics-keystone.py
  notify: restart sensu-client
