#!/bin/bash
# This script drops all expired entries from the keystone.token table.
# This is necessary, because otherwise the number of tokens would grow without bound.
# Intended to be run periodically by cron.

keystone-manage token_flush
