---
###########
# GENERAL #
###########
ceph_monitor:
  # ACTIVATE BOTH FSID AND MONITOR_SECRET VARIABLES FOR NON-VAGRANT DEPLOYMENT
  fsid: f3451e6a-f352-4a8a-bdeb-e97fde48de9e 
  monitor_secret: AQAin8tU4FRGFhAAmftBPgcpG/OLZ2qxkaMqMA== 
  cephx: true

  #############
  # OPENSTACK #
  #############

  openstack_config: true
  openstack_block_storage_pool: block_storage_pool

  openstack_keys:
    - { name: client.glance, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=block_storage_pool'" }
    - { name: client.cinder, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=block_storage_pool'"  }
