require 'spec_helper'

describe file('/etc/logrotate.d/apache2') do
  it { should exist }
  file_contents = [ '# Generated by Ansible.',
         '# Local modifications will be overwritten.',
         '',
         '/var/log/apache2/*.log',
         '{',
         '  daily',
         '  missingok',
         '  rotate 7',
         '  compress',
         '  delaycompress',
         '  notifempty',
         '  create 640 root adm',
         '  sharedscripts',
         '  postrotate if /etc/init.d/apache2 status > /dev/null ; then /etc/init.d/apache2 reload > /dev/null; fi;',
         '  endscript',
         '  prerotate if [ -d /etc/logrotate.d/httpd-prerotate ]; then run-parts /etc/logrotate.d/httpd-prerotate; fi;',
         '  endscript',
         '}']

  file_contents.each do |file_line|
    it { should contain file_line }
  end
end


files = ['access.log', 'error.log', 'other_vhosts_access.log']
files.each do |file|
  describe file("/var/log/apache2/#{file}") do
    it { should exist }
    it { should be_owned_by 'root' }
  end
end

describe file('/etc/openstack-dashboard/local_settings.py') do
  it { should contain 'DEBUG = False' }
end 
