---
- name: add mongodb arbiter to replica set
  command: mongo --host {{ endpoints.mongodb }} --eval rs.addArb(\"{{ primary_ip ~ ":" ~ mongodb.port | string}}\")
  when: inventory_hostname in groups['mongo_arbiter']
