---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.mongodb.repo }} {{ ansible_distribution_release }}/mongodb-org/3.0 multiverse'
        key_url: '{{ apt_repos.mongodb.key_url }}'
        key_id: '7F0CEB10'
        validate_certs: '{{ apt_repos.mongodb.validate_certs }}'
  - role: monitoring-common
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
