---
- name: permit access to ceilometer
  ufw: rule=allow to_port=8889 proto=tcp

- name: install ceilometer controller services
  upstart_service: name={{ item }}
                   user=ceilometer
                   cmd=/usr/local/bin/{{ item }}
  with_items:
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-agent-notification
    - ceilometer-agent-central
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
  notify: restart ceilometer services

- name: create ceilometer user in mongodb
  mongodb_user: database={{ ceilometer.mongodb_database }} name={{ ceilometer.mongodb_user }} password={{ ceilometer.mongodb_password }} roles='readWrite,dbAdmin' state=present
  when: inventory_hostname in groups['controller'][0]

- meta: flush_handlers

- name: start ceilometer services
  service: name={{ item }} state=started
  with_items:
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-agent-notification
    - ceilometer-agent-central
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
